'use client';

import React, { useState } from 'react';
import { 
  Calendar, 
  Download, 
  Upload, 
  FileText, 
  CheckCircle2, 
  AlertTriangle, 
  Clock, 
  Code, 
  Play, 
  Eye, 
  MoreVertical,
  Trash2,
  Edit3,
  Plus,
  Search,
  Filter
} from 'lucide-react';
import GlassPanel from '../../../../../components/ui/GlassPanel';
import BentoCard from '../../../../../components/ui/BentoCard';

// Types
type TabType = 'b2b' | 'b2cl' | 'b2cs' | 'exports' | 'hsn' | 'docs';

// Mock Data
const b2bInvoices = [
  { id: 'INV-S-001234', date: '18 Nov 2025', customer: 'XYZ Corporation', gstin: '29ABCDE1234F1Z5', pos: '29-Karnataka', value: 67890, taxable: 57535, igst: 10355, cgst: 0, sgst: 0, type: 'Regular', status: 'Validated' },
  { id: 'INV-S-001235', date: '18 Nov 2025', customer: 'Alpha Tech', gstin: '27PQRST5678H1Z2', pos: '27-Maharashtra', value: 12500, taxable: 10593, igst: 0, cgst: 953.5, sgst: 953.5, type: 'Regular', status: 'Validated' },
  { id: 'INV-S-001236', date: '17 Nov 2025', customer: 'Beta Retail', gstin: '27KLMNO4321J1Z9', pos: '27-Maharashtra', value: 45000, taxable: 38135, igst: 0, cgst: 3432.5, sgst: 3432.5, type: 'Regular', status: 'Warning' },
];

const b2csSummary = [
  { pos: '27-Maharashtra', rate: '18%', taxable: 245600, cgst: 22104, sgst: 22104, count: 20 },
  { pos: '27-Maharashtra', rate: '12%', taxable: 156780, cgst: 9406.8, sgst: 9406.8, count: 10 },
  { pos: '29-Karnataka', rate: '18%', taxable: 54400, igst: 9792, count: 4 },
];

export default function GSTR1DraftPage() {
  const [activeTab, setActiveTab] = useState<TabType>('b2b');
  const [selectedRows, setSelectedRows] = useState<string[]>([]);

  const toggleRowSelection = (id: string) => {
    setSelectedRows(prev => 
      prev.includes(id) ? prev.filter(rowId => rowId !== id) : [...prev, id]
    );
  };

  return (
    <div className="space-y-6 pb-20">
      
      {/* 1. PAGE HEADER */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">GSTR-1 Draft</h1>
          <p className="text-muted-foreground text-sm mt-1">Outward supplies return - auto-generated from sales register</p>
        </div>
        <div className="flex items-center gap-3">
           <div className="relative">
             <select className="appearance-none bg-zinc-900 border border-white/10 text-sm rounded-lg pl-9 pr-8 py-2 focus:ring-1 focus:ring-primary outline-none text-zinc-300 cursor-pointer hover:bg-zinc-800">
               <option>November 2025</option>
               <option>October 2025</option>
               <option>September 2025</option>
             </select>
             <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500 pointer-events-none" />
           </div>
           
           <button className="px-4 py-2 bg-zinc-900 border border-white/10 rounded-lg text-sm text-zinc-300 hover:text-white hover:bg-zinc-800 transition-all flex items-center gap-2">
             <Upload className="h-4 w-4" /> Import Excel
           </button>
           <button className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-sm font-medium shadow-lg shadow-emerald-500/20 transition-all flex items-center gap-2">
             <Play className="h-4 w-4" /> Auto-Generate Draft
           </button>
        </div>
      </div>

      {/* 2. STATUS CARD */}
      <GlassPanel className="p-6 relative overflow-hidden">
         <div className="flex flex-col md:flex-row justify-between gap-8">
            {/* Left: Status */}
            <div className="space-y-4">
               <div className="flex items-center gap-3">
                  <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 border border-emerald-500/20 text-sm font-medium">
                     <CheckCircle2 className="h-4 w-4" /> Draft Ready - 95% Complete
                  </span>
                  <span className="text-xs text-zinc-500">Last gen: 23 Nov, 6:45 PM</span>
               </div>
               <div className="flex items-center gap-2 text-sm text-zinc-400">
                  <span className="h-2 w-2 rounded-full bg-zinc-600"></span>
                  Generated by: <span className="text-white">Rahul Sharma</span>
               </div>
            </div>

            {/* Middle: Progress Checklist */}
            <div className="flex-1 border-l border-r border-white/5 px-8 hidden md:block">
               <p className="text-xs text-zinc-500 uppercase tracking-wider font-semibold mb-3">Sections Completed (5 of 6)</p>
               <div className="grid grid-cols-2 gap-y-2 gap-x-8">
                  <div className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="h-3 w-3" /> B2B Invoices (380)</div>
                  <div className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="h-3 w-3" /> Exports (10)</div>
                  <div className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="h-3 w-3" /> B2C Large (10)</div>
                  <div className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="h-3 w-3" /> HSN Summary</div>
                  <div className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="h-3 w-3" /> B2C Small (34)</div>
                  <div className="flex items-center gap-2 text-sm text-amber-500 animate-pulse"><AlertTriangle className="h-3 w-3" /> Documents (Missing)</div>
               </div>
            </div>

            {/* Right: Deadline & Actions */}
            <div className="space-y-4 text-right">
               <div>
                  <p className="text-xs text-zinc-500 uppercase tracking-wider font-semibold">Filing Deadline</p>
                  <div className="flex items-center justify-end gap-2 mt-1">
                     <Clock className="h-4 w-4 text-emerald-500" />
                     <span className="text-lg font-bold text-white">11 Dec 2025</span>
                     <span className="text-xs bg-emerald-500/10 text-emerald-500 px-2 py-0.5 rounded border border-emerald-500/20">18 Days Left</span>
                  </div>
               </div>
               <div className="flex justify-end gap-2">
                  <button className="px-3 py-1.5 rounded bg-zinc-900 border border-white/10 text-xs text-zinc-400 hover:text-white hover:bg-white/5 transition-colors flex items-center gap-1">
                     <Code className="h-3 w-3" /> Preview JSON
                  </button>
                  <button className="px-3 py-1.5 rounded bg-zinc-900 border border-white/10 text-xs text-zinc-400 hover:text-white hover:bg-white/5 transition-colors flex items-center gap-1">
                     <CheckCircle2 className="h-3 w-3" /> Validate
                  </button>
                  <button className="px-4 py-1.5 rounded bg-primary text-white text-xs font-bold hover:bg-primary/90 shadow-lg shadow-primary/20 transition-colors">
                     File Return
                  </button>
               </div>
            </div>
         </div>
      </GlassPanel>

      {/* 3. TAB NAVIGATION */}
      <div className="flex border-b border-white/5 overflow-x-auto">
         {[
            { id: 'b2b', label: 'B2B (380)' },
            { id: 'b2cl', label: 'B2C Large (10)' },
            { id: 'b2cs', label: 'B2C Small (34)' },
            { id: 'exports', label: 'Exports (10)' },
            { id: 'hsn', label: 'HSN Summary' },
            { id: 'docs', label: 'Documents' },
         ].map((tab) => (
            <button 
              key={tab.id}
              onClick={() => setActiveTab(tab.id as TabType)}
              className={`
                px-6 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                ${activeTab === tab.id ? 'border-primary text-white bg-white/5' : 'border-transparent text-zinc-500 hover:text-zinc-300 hover:bg-white/5'}
              `}
            >
               {tab.label}
            </button>
         ))}
      </div>

      {/* 4. CONTENT AREA */}
      <div className="min-h-[400px]">
         
         {/* TAB: B2B */}
         {activeTab === 'b2b' && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-200">
               {/* Controls */}
               <div className="flex justify-between items-center p-4 bg-zinc-900/50 border border-white/5 rounded-xl">
                  <div className="flex items-center gap-2">
                     <div className="relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-zinc-500" />
                        <input type="text" placeholder="Search invoices..." className="pl-9 pr-4 py-1.5 bg-zinc-900 border border-white/10 rounded-lg text-sm text-white focus:ring-1 focus:ring-primary outline-none w-64" />
                     </div>
                     <button className="p-1.5 bg-zinc-900 border border-white/10 rounded-lg text-zinc-400 hover:text-white"><Filter className="h-4 w-4" /></button>
                  </div>
                  <div className="flex gap-2">
                     <button className="px-3 py-1.5 rounded border border-white/10 text-zinc-300 text-xs hover:bg-white/5">Refresh from Sales</button>
                     <button className="px-3 py-1.5 rounded bg-zinc-800 text-white text-xs hover:bg-zinc-700 flex items-center gap-1"><Plus className="h-3 w-3" /> Add Manual Entry</button>
                  </div>
               </div>

               {/* Table */}
               <GlassPanel className="p-0 overflow-hidden">
                  <table className="w-full text-left text-sm">
                     <thead className="bg-white/5 text-zinc-500 font-medium">
                        <tr>
                           <th className="px-6 py-3 w-12"><input type="checkbox" className="rounded bg-zinc-800 border-zinc-600" /></th>
                           <th className="px-6 py-3">Invoice No</th>
                           <th className="px-6 py-3">Date</th>
                           <th className="px-6 py-3">Customer</th>
                           <th className="px-6 py-3">Place of Supply</th>
                           <th className="px-6 py-3 text-right">Value</th>
                           <th className="px-6 py-3 text-right">Taxable</th>
                           <th className="px-6 py-3 text-right">Tax</th>
                           <th className="px-6 py-3 text-center">Status</th>
                           <th className="px-6 py-3 text-right">Actions</th>
                        </tr>
                     </thead>
                     <tbody className="divide-y divide-white/5">
                        {b2bInvoices.map((inv) => (
                           <tr key={inv.id} className="hover:bg-white/5 transition-colors group">
                              <td className="px-6 py-4"><input type="checkbox" className="rounded bg-zinc-800 border-zinc-600" /></td>
                              <td className="px-6 py-4 font-medium text-white cursor-pointer hover:text-primary">{inv.id}</td>
                              <td className="px-6 py-4 text-zinc-400">{inv.date}</td>
                              <td className="px-6 py-4">
                                 <div className="flex flex-col">
                                    <span className="text-white">{inv.customer}</span>
                                    <span className="text-[10px] text-zinc-500 font-mono">{inv.gstin}</span>
                                 </div>
                              </td>
                              <td className="px-6 py-4 text-zinc-400">{inv.pos}</td>
                              <td className="px-6 py-4 text-right text-white font-mono">₹{inv.value.toLocaleString()}</td>
                              <td className="px-6 py-4 text-right text-zinc-300 font-mono">₹{inv.taxable.toLocaleString()}</td>
                              <td className="px-6 py-4 text-right text-zinc-300 font-mono">₹{(inv.igst + inv.cgst + inv.sgst).toLocaleString()}</td>
                              <td className="px-6 py-4 text-center">
                                 <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium border ${inv.status === 'Validated' ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20' : 'bg-amber-500/10 text-amber-500 border-amber-500/20'}`}>
                                    {inv.status === 'Validated' ? <CheckCircle2 className="h-3 w-3" /> : <AlertTriangle className="h-3 w-3" />}
                                    {inv.status}
                                 </span>
                              </td>
                              <td className="px-6 py-4 text-right">
                                 <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <button className="p-1.5 hover:bg-white/10 rounded text-zinc-400 hover:text-white"><Edit3 className="h-4 w-4" /></button>
                                    <button className="p-1.5 hover:bg-white/10 rounded text-zinc-400 hover:text-red-400"><Trash2 className="h-4 w-4" /></button>
                                 </div>
                              </td>
                           </tr>
                        ))}
                     </tbody>
                  </table>
                  {/* Summary Row */}
                  <div className="bg-zinc-900/50 border-t border-white/10 px-6 py-3 flex justify-between items-center text-sm font-medium">
                     <span className="text-zinc-400">Total: 380 Invoices</span>
                     <div className="flex gap-8">
                        <span className="text-zinc-300">Taxable: <span className="text-white">₹64,56,789</span></span>
                        <span className="text-zinc-300">Tax: <span className="text-white">₹12,22,000</span></span>
                        <span className="text-zinc-300">Total: <span className="text-white font-bold">₹76,78,789</span></span>
                     </div>
                  </div>
               </GlassPanel>
            </div>
         )}

         {/* TAB: B2C Small */}
         {activeTab === 'b2cs' && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-200">
               <div className="p-4 bg-blue-500/10 border border-blue-500/20 rounded-xl text-sm text-blue-200 flex items-center gap-2">
                  <FileText className="h-4 w-4" />
                  Data aggregated based on Place of Supply and Tax Rate for invoices &lt; ₹2.5 Lakhs.
               </div>
               <GlassPanel className="p-0 overflow-hidden">
                  <table className="w-full text-left text-sm">
                     <thead className="bg-white/5 text-zinc-500 font-medium">
                        <tr>
                           <th className="px-6 py-3">Place of Supply</th>
                           <th className="px-6 py-3 text-center">Tax Rate</th>
                           <th className="px-6 py-3 text-right">Taxable Value</th>
                           <th className="px-6 py-3 text-right">IGST</th>
                           <th className="px-6 py-3 text-right">CGST</th>
                           <th className="px-6 py-3 text-right">SGST</th>
                           <th className="px-6 py-3 text-center">Invoice Count</th>
                           <th className="px-6 py-3 text-right">Actions</th>
                        </tr>
                     </thead>
                     <tbody className="divide-y divide-white/5">
                        {b2csSummary.map((row, idx) => (
                           <tr key={idx} className="hover:bg-white/5 transition-colors">
                              <td className="px-6 py-4 text-white">{row.pos}</td>
                              <td className="px-6 py-4 text-center"><span className="bg-zinc-800 px-2 py-1 rounded text-xs text-zinc-300">{row.rate}</span></td>
                              <td className="px-6 py-4 text-right font-mono text-zinc-300">₹{row.taxable.toLocaleString()}</td>
                              <td className="px-6 py-4 text-right font-mono text-zinc-400">₹{(row.igst || 0).toLocaleString()}</td>
                              <td className="px-6 py-4 text-right font-mono text-zinc-400">₹{(row.cgst || 0).toLocaleString()}</td>
                              <td className="px-6 py-4 text-right font-mono text-zinc-400">₹{(row.sgst || 0).toLocaleString()}</td>
                              <td className="px-6 py-4 text-center text-white font-bold">{row.count}</td>
                              <td className="px-6 py-4 text-right">
                                 <button className="text-xs text-primary hover:underline">Edit</button>
                              </td>
                           </tr>
                        ))}
                     </tbody>
                  </table>
               </GlassPanel>
            </div>
         )}

         {/* Placeholder for other tabs */}
         {(activeTab !== 'b2b' && activeTab !== 'b2cs') && (
            <div className="flex flex-col items-center justify-center h-64 text-zinc-500 bg-zinc-900/30 border border-white/5 rounded-xl animate-in fade-in">
               <FileText className="h-12 w-12 mb-4 opacity-20" />
               <p>Section content available in full version.</p>
            </div>
         )}

      </div>
    </div>
  );
}
